In [1]:
import pandas as pd
import statistics

In [2]:
dataset = pd.read_csv("cm1.csv")
dataset

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                            1.1                             1.4   
1                            1.0                             1.0   
2                           24.0                             5.0   
3                           20.0                             4.0   
4                           24.0                             6.0   
..                           ...                             ...   
493                         47.0                             3.0   
494                         24.0                             4.0   
495                         82.0                            11.0   
496                         10.0                             2.0   
497                         28.0                             6.0   

     McCabe "essential complexity”  McCabe "design complexity”  \
0                              1.4                         1.4   
1                              1.0                         1.0   
2                              1.0                         3.0   
3                              4.0                         2.0   
4                              6.0                         2.0   
..                             ...                         ...   
493                            1.0                         3.0   
494                            3.0                         3.0   
495                            3.0                        10.0   
496                            1.0                         1.0   
497                            5.0                         5.0   

     Halstead total operators + operands  Halstead "volume”  \
0                                    1.3               1.30   
1                                    1.0               1.00   
2                                   63.0             309.13   
3                                   47.0             215.49   
4                                   72.0             346.13   
..                                   ...                ...   
493                                256.0            1563.78   
494                                107.0             587.63   
495                                475.0            3155.83   
496                                 32.0             150.41   
497                                104.0             564.33   

     Halstead "program length”  Halstead "difficulty”  \
0                         1.30                   1.30   
1                         1.00                   1.00   
2                         0.11                   9.50   
3                         0.06                  16.00   
4                         0.06                  17.33   
..                         ...                    ...   
493                       0.04                  28.00   
494                       0.05                  19.13   
495                       0.02                  44.71   
496                       0.15                   6.50   
497                       0.06                  16.09   

     Halstead "intelligence”  Halstead "effort”  ...  Halstead's line count  \
0                       1.30               1.30  ...                      2   
1                       1.00               1.00  ...                      1   
2                      32.54            2936.77  ...                      1   
3                      13.47            3447.89  ...                      0   
4                      19.97            5999.58  ...                      0   
..                       ...                ...  ...                    ...   
493                    55.85           43785.90  ...                      2   
494                    30.72           11241.58  ...                      1   
495                    70.59          141084.24  ...                      9   
496                    23.14             977.69  ...                      1   
497                    35.08            9078.38  ...                      2   

    

In [3]:
# label encoding 0 and 1 for target variable
from sklearn.preprocessing import LabelEncoder as LE
L_Defects = LE()

New_data = dataset
New_data["defects"] = L_Defects.fit_transform(New_data["defects"])
New_data.head()

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                          1.1                             1.4   
1                          1.0                             1.0   
2                         24.0                             5.0   
3                         20.0                             4.0   
4                         24.0                             6.0   

   McCabe "essential complexity”  McCabe "design complexity”  \
0                            1.4                         1.4   
1                            1.0                         1.0   
2                            1.0                         3.0   
3                            4.0                         2.0   
4                            6.0                         2.0   

   Halstead total operators + operands  Halstead "volume”  \
0                                  1.3               1.30   
1                                  1.0               1.00   
2                                 63.0             309.13   
3                                 47.0             215.49   
4                                 72.0             346.13   

   Halstead "program length”  Halstead "difficulty”  Halstead "intelligence”  \
0                       1.30                   1.30                     1.30   
1                       1.00                   1.00                     1.00   
2                       0.11                   9.50                    32.54   
3                       0.06                  16.00                    13.47   
4                       0.06                  17.33                    19.97   

   Halstead "effort”  ...  Halstead's line count  \
0               1.30  ...                      2   
1               1.00  ...                      1   
2            2936.77  ...                      1   
3            3447.89  ...                      0   
4            5999.58  ...                      0   

   Halstead's count of lines of comments  Halstead's count of blank  \
0                                      2                          2   
1                                      1                          1   
2                                      0                          6   
3                                      0                          3   
4                                      0                          3   

   lineslOCodeAndComment  unique operators  unique operands  total operators  \
0                      2               1.2              1.2              1.2   
1                      1               1.0              1.0              1.0   
2                      0              15.0             15.0             44.0   
3                      0              16.0              8.0             31.0   
4                      0              16.0             12.0             46.0   

   total operands  branchCount of the flow graph  defects  
0             1.2                            1.4        0  
1             1.0                            1.0        1  
2            19.0                            9.0        0  
3            16.0                            7.0        0  
4            26.0                           11.0        0  

[5 rows x 22 columns]

In [14]:
# creating x and y variables that will store NonDefective and Defective
X=New_data.loc[New_data['defects']==0]
Y=New_data.loc[New_data['defects']==1]
X

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                            1.1                             1.4   
2                           24.0                             5.0   
3                           20.0                             4.0   
4                           24.0                             6.0   
5                           24.0                             6.0   
..                           ...                             ...   
445                          9.0                             3.0   
446                         11.0                             3.0   
447                          4.0                             1.0   
448                          3.0                             1.0   
449                         12.0                             3.0   

     McCabe "essential complexity”  McCabe "design complexity”  \
0                              1.4                         1.4   
2                              1.0                         3.0   
3                              4.0                         2.0   
4                              6.0                         2.0   
5                              6.0                         2.0   
..                             ...                         ...   
445                            1.0                         1.0   
446                            1.0                         1.0   
447                            1.0                         1.0   
448                            1.0                         1.0   
449                            1.0                         1.0   

     Halstead total operators + operands  Halstead "volume”  \
0                                    1.3               1.30   
2                                   63.0             309.13   
3                                   47.0             215.49   
4                                   72.0             346.13   
5                                   72.0             346.13   
..                                   ...                ...   
445                                 41.0             170.97   
446                                 49.0             215.22   
447                                 13.0              39.00   
448                                  7.0              19.65   
449                                 51.0             227.43   

     Halstead "program length”  Halstead "difficulty”  \
0                         1.30                   1.30   
2                         0.11                   9.50   
3                         0.06                  16.00   
4                         0.06                  17.33   
5                         0.06                  17.33   
..                         ...                    ...   
445                       0.07                  14.14   
446                       0.07                  14.67   
447                       0.33                   3.00   
448                       0.40                   2.50   
449                       0.10                  10.42   

     Halstead "intelligence”  Halstead "effort”  ...  Halstead's line count  \
0                       1.30               1.30  ...                      2   
2                      32.54            2936.77  ...                      1   
3                      13.47            3447.89  ...                      0   
4                      19.97            5999.58  ...                      0   
5                      19.97            5999.58  ...                      0   
..                       ...                ...  ...                    ...   
445                    12.09            2417.96  ...                      0   
446                    14.67            3156.61  ...                      0   
447                    13.00             117.00  ...                      0   
448                     7.86              49.13  ...                      0   
449                    21.83            2369.07  ...                      0   

    

In [16]:
# checking which is  NonDefective and Defective based on their frequency of occurence
if len(X)>len(Y):
    NonDefective=X
    Defective=Y
else :
    Defective=X
    NonDefective=Y
NonDefective

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                            1.1                             1.4   
2                           24.0                             5.0   
3                           20.0                             4.0   
4                           24.0                             6.0   
5                           24.0                             6.0   
..                           ...                             ...   
445                          9.0                             3.0   
446                         11.0                             3.0   
447                          4.0                             1.0   
448                          3.0                             1.0   
449                         12.0                             3.0   

     McCabe "essential complexity”  McCabe "design complexity”  \
0                              1.4                         1.4   
2                              1.0                         3.0   
3                              4.0                         2.0   
4                              6.0                         2.0   
5                              6.0                         2.0   
..                             ...                         ...   
445                            1.0                         1.0   
446                            1.0                         1.0   
447                            1.0                         1.0   
448                            1.0                         1.0   
449                            1.0                         1.0   

     Halstead total operators + operands  Halstead "volume”  \
0                                    1.3               1.30   
2                                   63.0             309.13   
3                                   47.0             215.49   
4                                   72.0             346.13   
5                                   72.0             346.13   
..                                   ...                ...   
445                                 41.0             170.97   
446                                 49.0             215.22   
447                                 13.0              39.00   
448                                  7.0              19.65   
449                                 51.0             227.43   

     Halstead "program length”  Halstead "difficulty”  \
0                         1.30                   1.30   
2                         0.11                   9.50   
3                         0.06                  16.00   
4                         0.06                  17.33   
5                         0.06                  17.33   
..                         ...                    ...   
445                       0.07                  14.14   
446                       0.07                  14.67   
447                       0.33                   3.00   
448                       0.40                   2.50   
449                       0.10                  10.42   

     Halstead "intelligence”  Halstead "effort”  ...  Halstead's line count  \
0                       1.30               1.30  ...                      2   
2                      32.54            2936.77  ...                      1   
3                      13.47            3447.89  ...                      0   
4                      19.97            5999.58  ...                      0   
5                      19.97            5999.58  ...                      0   
..                       ...                ...  ...                    ...   
445                    12.09            2417.96  ...                      0   
446                    14.67            3156.61  ...                      0   
447                    13.00             117.00  ...                      0   
448                     7.86              49.13  ...                      0   
449                    21.83            2369.07  ...                      0   

    

In [6]:
#data preprocessing
X= New_data.drop('defects', axis='columns')
Y= New_data['defects']

In [10]:
To_Be_Removed = pd.DataFrame(columns=['index','membership_count'])    
To_Be_Removed

NonDefective.index[0]

0

In [8]:
import numpy as np

To_Be_Removed = pd.DataFrame(columns=['index','membership_count'])
data = []
distances_NonDefective = []
NonDefective_neighbors_ids = []

for i in range(0,len(Defective)):
    # KNN search function to find n nearest points using eucliedian dist and
    # placing them in colonial neigbhors
    new_data_point = np.array(X.loc[Defective.index[i]])
    distances = np.linalg.norm(X - new_data_point, axis=1)

    # K=10 because IR value is 10 for the given dataset cm1
    k = 10
    K_neighbors = distances.argsort()[1:k+1]

    print(K_neighbors)
    # finding the NonDefective colonial neighbors from all the colonial neighbors that
    # were found earlier
    for i in K_neighbors:
        if(Y[i]==NonDefective.loc[NonDefective.index[0]]['defects']):
            data.append(X.loc[i])
            distances_NonDefective.append(distances[i])
            NonDefective_neighbors_ids.append(i)

Neighbors = pd.DataFrame()
Neighbors[0] = NonDefective_neighbors_ids
Neighbors[1] = distances_NonDefective
print(Neighbors)
print(Neighbors.loc[0][0])

[  0 397 398 399 162 181 281 403 208 207]
[ 10 279 454 350 172 471 260  53 254 469]
[  8 209  82  58 334 425 423 186 428 462]
[294 439 351 370 296 472  67 360 435 275]
[477 189 359 178 124 414 415  40 222 277]
[350 172 471 450  10 279 368  53 260 254]
[ 70 121 290 434 253 371 274 465 188 457]
[470 127  14  67  44 472  43 296 351 452]
[495  28 465 365 188  50 371 112 241 282]
[466 255 361 461 273 113  29 291 102 139]
[459 151 146 145 413 171 323 249 233 266]
[459 151 146 145 413 171 323 249 233 266]
[273 113  29 291 102 361 139 255 468 484]
[ 18 423 476  38 147  82 451 497 334 209]
[300 118 274 358 121 290 484  70 455 468]
[ 15  39 214 388 213 311 336  93  79 104]
[188 371 457 495 253  28 434 455 365  70]
[458 255 361 461 273 113  29 291 102 139]
[492 211 240 482 206 357 126 308 157 276]
[484 358 118 300 463 139 274 121 290  70]
[ 53 254 327 420 369 367 260 429 187  41]
[456 127  14  67 472  44  43 296 351 452]
[172 454 350 450  10 279 368  53 469 254]
[351  67 296 452 294  14 370 439 3

In [23]:
#calculating the membership count
for j in range(0,len(Neighbors)):
    i = Neighbors.loc[j][0]
    if To_Be_Removed['index'].isin([i]).any().any():
        To_Be_Removed.loc[To_Be_Removed['index']==i,'membership_count']+=1
    else:
        new_row = {'index':i,'membership_count':1}
        To_Be_Removed=To_Be_Removed.append(new_row, ignore_index=True)
To_Be_Removed

index  membership_count
0      0.0               1.0
1    397.0               1.0
2    398.0               1.0
3    399.0               1.0
4    162.0               1.0
..     ...               ...
238  422.0               1.0
239   76.0               1.0
240   55.0               1.0
241   63.0               1.0
242  328.0               1.0

[243 rows x 2 columns]

In [25]:
# checking those that have membership count more than 1
To_Be_Removed = To_Be_Removed.loc[To_Be_Removed['membership_count']>1]
To_Be_Removed

index  membership_count
10    10.0               3.0
11   279.0               3.0
12   350.0               3.0
13   172.0               3.0
14   260.0               3.0
..     ...               ...
163   13.0               2.0
164  185.0               2.0
165  427.0               2.0
167  130.0               2.0
169  169.0               2.0

[107 rows x 2 columns]

In [26]:
#sorting the final elimination based on value of index because while droping in 
#the last step indexes will be changed , so to avoid wrong instance elimination 
# we sort them in decreasing order of their indices
To_Be_Removed = To_Be_Removed.sort_values(["index"], ascending=False)
To_Be_Removed

index  membership_count
27   439.0               2.0
33   435.0               2.0
48   434.0               2.0
108  429.0               2.0
25   428.0               2.0
..     ...               ...
57    28.0               3.0
80    18.0               3.0
54    14.0               3.0
163   13.0               2.0
10    10.0               3.0

[107 rows x 2 columns]

In [27]:
#dropping those instances that were chosen for final elimination
for i in To_Be_Removed['index']:
    dataset.drop(dataset.index[int(i)],inplace=True)
    
dataset

McCabe's line count of code  McCabe "cyclomatic complexity”  \
0                            1.1                             1.4   
1                            1.0                             1.0   
2                           24.0                             5.0   
3                           20.0                             4.0   
4                           24.0                             6.0   
..                           ...                             ...   
493                         47.0                             3.0   
494                         24.0                             4.0   
495                         82.0                            11.0   
496                         10.0                             2.0   
497                         28.0                             6.0   

     McCabe "essential complexity”  McCabe "design complexity”  \
0                              1.4                         1.4   
1                              1.0                         1.0   
2                              1.0                         3.0   
3                              4.0                         2.0   
4                              6.0                         2.0   
..                             ...                         ...   
493                            1.0                         3.0   
494                            3.0                         3.0   
495                            3.0                        10.0   
496                            1.0                         1.0   
497                            5.0                         5.0   

     Halstead total operators + operands  Halstead "volume”  \
0                                    1.3               1.30   
1                                    1.0               1.00   
2                                   63.0             309.13   
3                                   47.0             215.49   
4                                   72.0             346.13   
..                                   ...                ...   
493                                256.0            1563.78   
494                                107.0             587.63   
495                                475.0            3155.83   
496                                 32.0             150.41   
497                                104.0             564.33   

     Halstead "program length”  Halstead "difficulty”  \
0                         1.30                   1.30   
1                         1.00                   1.00   
2                         0.11                   9.50   
3                         0.06                  16.00   
4                         0.06                  17.33   
..                         ...                    ...   
493                       0.04                  28.00   
494                       0.05                  19.13   
495                       0.02                  44.71   
496                       0.15                   6.50   
497                       0.06                  16.09   

     Halstead "intelligence”  Halstead "effort”  ...  Halstead's line count  \
0                       1.30               1.30  ...                      2   
1                       1.00               1.00  ...                      1   
2                      32.54            2936.77  ...                      1   
3                      13.47            3447.89  ...                      0   
4                      19.97            5999.58  ...                      0   
..                       ...                ...  ...                    ...   
493                    55.85           43785.90  ...                      2   
494                    30.72           11241.58  ...                      1   
495                    70.59          141084.24  ...                      9   
496                    23.14             977.69  ...                      1   
497                    35.08            9078.38  ...                      2   

    

In [28]:
# Saving our new improved dataset into a new .csv file
dataset.to_csv("D.csv")